apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx
    pod-template-hash: 58bfb7c6b
  name: nginx-58bfb7c6b
  namespace: jegan
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      pod-template-hash: 58bfb7c6b
  template:
    metadata:
      labels:
        app: nginx
        pod-template-hash: 58bfb7c6b
    spec:
      containers:
      - image: bitnami/nginx
        imagePullPolicy: Always
        name: nginx
